### ISSUE TITLE
Machine is force to shutdown and destroyed after puppet is installed

### ISSUE THREAD

**Issue by mlt** [petems/vagrant-puppet-install#42]
I'm not sure what is going on. I would like to have a newer puppet on ubuntu/precise32 box. So I gave a try to this vagrant plugin. I tried :latest and 3.7.5 with same outcome. Host machine is Windows 7 Enterprise 64 bit. Vagrant is 1.8.1.
Here is the output:
```ruby
==> default: Installing Puppet 3.7.5 package...
==> default: 03:45:20 +0000 INFO: Version parameter defined: 3.7.5
==> default: 03:45:20 +0000 INFO: Downloading Puppet 3.7.5 for ubuntu...
==> default: 03:45:20 +0000 INFO: Ubuntu platform! Lets get you a DEB...
==> default: 03:45:20 +0000 INFO: Downloading http://apt.puppetlabs.com/puppetlabs-release-precise.deb
==> default: 03:45:20 +0000 INFO:   to file /tmp/install.sh.1886.4660/puppetlabs-release-precise.deb
==> default: 03:45:20 +0000 INFO: Trying wget...
==> default: 03:45:20 +0000 INFO: installing with dpkg...
==> default: Selecting previously unselected package puppetlabs-release.
==> default: (Reading database ... 
==> default: 66899 files and directories currently installed.)
==> default: Unpacking puppetlabs-release (from .../puppetlabs-release-precise.deb) ...
==> default: Setting up puppetlabs-release (1.0-11) ...
==> default: Get:1 http://apt.puppetlabs.com precise Release.gpg [836 B]
==> default: Get:2 http://apt.puppetlabs.com precise Release [54.4 kB]
==> default: Get:3 http://apt.puppetlabs.com precise/main Sources [88.8 kB]
==> default: Hit http://archive.ubuntu.com precise Release.gpg
==> default: Hit http://security.ubuntu.com precise-security Release.gpg
==> default: Get:4 http://apt.puppetlabs.com precise/dependencies Sources [9,250 B]
==> default: Get:5 http://apt.puppetlabs.com precise/main i386 Packages [102 kB]
==> default: Get:6 http://apt.puppetlabs.com precise/dependencies i386 Packages [6,420 B]
==> default: Hit http://archive.ubuntu.com precise-updates Release.gpg
==> default: Ign http://apt.puppetlabs.com precise/dependencies TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security Release
==> default: Ign http://apt.puppetlabs.com precise/main TranslationIndex
==> default: Get:7 http://archive.ubuntu.com precise-backports Release.gpg [198 B]
==> default: Get:8 http://security.ubuntu.com precise-security/main Sources [140 kB]
==> default: Hit http://archive.ubuntu.com precise Release
==> default: Hit http://archive.ubuntu.com precise-updates Release
==> default: Get:9 http://archive.ubuntu.com precise-backports Release [55.5 kB]
==> default: Get:10 http://security.ubuntu.com precise-security/universe Sources [45.7 kB]
==> default: Ign http://apt.puppetlabs.com precise/dependencies Translation-en_US
==> default: Ign http://apt.puppetlabs.com precise/dependencies Translation-en
==> default: Ign http://apt.puppetlabs.com precise/main Translation-en_US
==> default: Hit http://security.ubuntu.com precise-security/main i386 Packages
==> default: Ign http://apt.puppetlabs.com precise/main Translation-en
==> default: Hit http://security.ubuntu.com precise-security/universe i386 Packages
==> default: Get:11 http://archive.ubuntu.com precise/main Sources [934 kB]
==> default: Hit http://security.ubuntu.com precise-security/main TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security/universe TranslationIndex
==> default: Hit http://security.ubuntu.com precise-security/main Translation-en
==> default: Hit http://security.ubuntu.com precise-security/universe Translation-en
==> default: Get:12 http://archive.ubuntu.com precise/restricted Sources [5,470 B]
==> default: Get:13 http://archive.ubuntu.com precise/universe Sources [5,019 kB]
==> default: Get:14 http://archive.ubuntu.com precise/multiverse Sources [155 kB]
==> default: Hit http://archive.ubuntu.com precise/main i386 Packages
==> default: Hit http://archive.ubuntu.com precise/restricted i386 Packages
==> default: Hit http://archive.ubuntu.com precise/universe i386 Packages
==> default: Hit http://archive.ubuntu.com precise/multiverse i386 Packages
==> default: Hit http://archive.ubuntu.com precise/main TranslationIndex
==> default: Hit http://archive.ubuntu.com precise/multiverse TranslationIndex
==> default: Hit http://archive.ubuntu.com precise/restricted TranslationIndex
==> default: Hit http://archive.ubuntu.com precise/universe TranslationIndex
==> default: Get:15 http://archive.ubuntu.com precise-updates/main Sources [495 kB]
==> default: Get:16 http://archive.ubuntu.com precise-updates/restricted Sources [8,708 B]
==> default: Get:17 http://archive.ubuntu.com precise-updates/universe Sources [124 kB]
==> default: Get:18 http://archive.ubuntu.com precise-updates/multiverse Sources [10.2 kB]
==> default: Hit http://archive.ubuntu.com precise-updates/main i386 Packages
==> default: Hit http://archive.ubuntu.com precise-updates/restricted i386 Packages
==> default: Hit http://archive.ubuntu.com precise-updates/universe i386 Packages
==> default: Hit http://archive.ubuntu.com precise-updates/multiverse i386 Packages
==> default: Hit http://archive.ubuntu.com precise-updates/main TranslationIndex
==> default: Hit http://archive.ubuntu.com precise-updates/multiverse TranslationIndex
==> default: Hit http://archive.ubuntu.com precise-updates/restricted TranslationIndex
==> default: Hit http://archive.ubuntu.com precise-updates/universe TranslationIndex
==> default: Get:19 http://archive.ubuntu.com precise-backports/main Sources [5,922 B]
==> default: Get:20 http://archive.ubuntu.com precise-backports/restricted Sources [28 B]
==> default: Get:21 http://archive.ubuntu.com precise-backports/universe Sources [43.5 kB]
==> default: Get:22 http://archive.ubuntu.com precise-backports/multiverse Sources [5,750 B]
==> default: Get:23 http://archive.ubuntu.com precise-backports/main i386 Packages [6,478 B]
==> default: Get:24 http://archive.ubuntu.com precise-backports/restricted i386 Packages [28 B]
==> default: Get:25 http://archive.ubuntu.com precise-backports/universe i386 Packages [45.6 kB]
==> default: Get:26 http://archive.ubuntu.com precise-backports/multiverse i386 Packages [5,413 B]
==> default: Get:27 http://archive.ubuntu.com precise-backports/main TranslationIndex [202 B]
==> default: Get:28 http://archive.ubuntu.com precise-backports/multiverse TranslationIndex [202 B]
==> default: Get:29 http://archive.ubuntu.com precise-backports/restricted TranslationIndex [193 B]
==> default: Get:30 http://archive.ubuntu.com precise-backports/universe TranslationIndex [205 B]
==> default: Hit http://archive.ubuntu.com precise/main Translation-en
==> default: Hit http://archive.ubuntu.com precise/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com precise/restricted Translation-en
==> default: Hit http://archive.ubuntu.com precise/universe Translation-en
==> default: Hit http://archive.ubuntu.com precise-updates/main Translation-en
==> default: Hit http://archive.ubuntu.com precise-updates/multiverse Translation-en
==> default: Hit http://archive.ubuntu.com precise-updates/restricted Translation-en
==> default: Hit http://archive.ubuntu.com precise-updates/universe Translation-en
==> default: Get:31 http://archive.ubuntu.com precise-backports/main Translation-en [5,737 B]
==> default: Get:32 http://archive.ubuntu.com precise-backports/multiverse Translation-en [4,852 B]
==> default: Get:33 http://archive.ubuntu.com precise-backports/restricted Translation-en [28 B]
==> default: Get:34 http://archive.ubuntu.com precise-backports/universe Translation-en [35.6 kB]
==> default: Fetched 7,415 kB in 22s (331 kB/s)
==> default: Reading package lists...

==> default: Reading package lists...

==> default: Building dependency tree...

==> default: Reading state information...

==> default: The following extra packages will be installed:
==> default:   facter hiera libjson-ruby ruby-json virt-what
==> default: Suggested packages:
==> default:   puppet-el vim-puppet ruby-selinux libselinux-ruby1.8 librrd-ruby1.9.1
==> default:   librrd-ruby1.8
==> default: The following NEW packages will be installed:
==> default:   hiera libjson-ruby ruby-json virt-what
==> default: The following packages will be upgraded:
==> default:   facter puppet puppet-common
==> default: 3 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 1,862 kB of archives.
==> default: After this operation, 4,750 kB of additional disk space will be used.
==> default: Get:1 http://apt.puppetlabs.com/ precise/main facter all 2.4.6-1puppetlabs1 [87.8 kB]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ precise/universe virt-what i386 1.11-1 [12.8 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ precise/universe ruby-json i386 1.6.3-1 [72.4 kB]
==> default: Get:4 http://apt.puppetlabs.com/ precise/main hiera all 1.3.4-1puppetlabs1 [12.9 kB]
==> default: Get:5 http://apt.puppetlabs.com/ precise/main puppet-common all 3.7.5-1puppetlabs1 [1,665 kB]
==> default: Get:6 http://archive.ubuntu.com/ubuntu/ precise/universe libjson-ruby all 1.6.3-1 [1,588 B]
==> default: Get:7 http://apt.puppetlabs.com/ precise/main puppet all 3.7.5-1puppetlabs1 [9,622 B]
==> default:   
==> default: puppet-common:i386
==> default:  conflicts with 
==> default: puppet:i386

==> default:     
==> default: puppet:i386
==> default:  conflicts with 
==> default: puppet-common:i386

==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 1,862 kB in 0s (3,152 kB/s)
==> default: Selecting previously unselected package virt-what.
==> default: (Reading database ... 
==> default: 66906 files and directories currently installed.)
==> default: Unpacking virt-what (from .../virt-what_1.11-1_i386.deb) ...
==> default: Preparing to replace facter 1.6.5-1ubuntu1.2 (using .../facter_2.4.6-1puppetlabs1_all.deb) ...
==> default: Unpacking replacement facter ...
==> default: Selecting previously unselected package ruby-json.
==> default: Unpacking ruby-json (from .../ruby-json_1.6.3-1_i386.deb) ...
==> default: Selecting previously unselected package libjson-ruby.
==> default: Unpacking libjson-ruby (from .../libjson-ruby_1.6.3-1_all.deb) ...
==> default: Selecting previously unselected package hiera.
==> default: Unpacking hiera (from .../hiera_1.3.4-1puppetlabs1_all.deb) ...
==> default: Processing triggers for man-db ...
==> default: dpkg: puppet-common: dependency problems, but removing anyway as you requested:
==> default:  puppet depends on puppet-common (= 2.7.11-1ubuntu2.7).
==> default: (Reading database ... 
==> default: 67050 files and directories currently installed.)
==> default: Removing puppet-common ...
==> default: Processing triggers for man-db ...
==> default: (Reading database ... 
==> default: 66065 files and directories currently installed.)
==> default: Preparing to replace puppet 2.7.11-1ubuntu2.7 (using .../puppet_3.7.5-1puppetlabs1_all.deb) ...
==> default: Unpacking replacement puppet ...
==> default: Selecting previously unselected package puppet-common.
==> default: Unpacking puppet-common (from .../puppet-common_3.7.5-1puppetlabs1_all.deb) ...
==> default: Processing triggers for ureadahead ...
==> default: Processing triggers for man-db ...
==> default: Setting up ruby-json (1.6.3-1) ...
==> default: Setting up libjson-ruby (1.6.3-1) ...
==> default: Setting up hiera (1.3.4-1puppetlabs1) ...
==> default: Setting up virt-what (1.11-1) ...
==> default: Setting up facter (2.4.6-1puppetlabs1) ...
==> default: Setting up puppet-common (3.7.5-1puppetlabs1) ...
==> default: Installing new version of config file /etc/puppet/puppet.conf ...
==> default: Installing new version of config file /etc/logcheck/ignore.d.server/puppet-common ...
==> default: Setting up puppet (3.7.5-1puppetlabs1) ...
==> default: Installing new version of config file /etc/default/puppet ...
==> default: Installing new version of config file /etc/init.d/puppet ...
==> default:  * Starting puppet agent

==> default: puppet not configured to start, please edit /etc/default/puppet to enable
==> default:    ...done.
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
C:/Users/user/.vagrant.d/gems/gems/vagrant-puppet-install-4.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:176:in `unlink': Permission denied @ unlink_internal - C:/Users/user/.vagrant.d/tmp/1459568720-install.sh (Errno::EACCES)
	from C:/Users/user/.vagrant.d/gems/gems/vagrant-puppet-install-4.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:176:in `recover'
	from C:/Users/user/.vagrant.d/gems/gems/vagrant-puppet-install-4.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:42:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/Users/user/.vagrant.d/gems/gems/vagrant-librarian-puppet-0.9.1/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:35:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/import.rb:74:in `import'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/import.rb:13:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by petems** [comment]
Hmm, looks like a permissions issue when it tries to unlink the script on the Windows machine.

```
==> default: Destroying VM and associated drives...
C:/Users/user/.vagrant.d/gems/gems/vagrant-puppet-install-4.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:176:in `unlink': Permission denied @ unlink_internal - C:/Users/user/.vagrant.d/tmp/1459568720-install.sh (Errno::EACCES)
    from C:/Users/user/.vagrant.d/gems/gems/vagrant-puppet-install-4.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:176:in `recover'
    from C:/Users/user/.vagrant.d/gems/gems/vagrant-puppet-install-4.0.0/lib/vagrant-puppet-install/action/install_puppet.rb:42:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
```

Doing some quick googling, looks like a problem with Ruby and Windows. This looks like it might help:
http://alx.github.io/2009/01/27/ruby-wundows-unlink.html

I don't have a Windows machine to test on right now, but might be able to try on a VM.

**Comment by petems** [comment]
Aha, looks like the Chef version of this plugin already fixed this! :smile: 

https://github.com/chef/vagrant-omnibus/pull/65

I'll see if I can get that merged in and released soon! :+1:

**Comment by mlt** [comment]
The fix is brutal. I wonder what is holding the file. Nevertheless, I confirm, it works! Thank you!
